from __future__ import annotations

import json
import os
import re
import shutil
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path


@dataclass(frozen=True)
class TrainingBundleConfig:
    backend: str
    parent_model: str
    training_data: str
    labels_or_config: str
    initialization_video: str
    training_script: str
    output_directory: str
    model_name: str
    epochs: int
    batch_size: int
    learning_rate: float
    random_seed: int
    remote_host: str
    remote_user: str
    remote_root: str
    slurm_account: str
    slurm_partition: str
    walltime: str
    gpus: int
    cpus: int
    memory_gb: int


def safe_name(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", value.strip()).strip("._")
    return cleaned or "training_run"


def validate_config(config: TrainingBundleConfig) -> list[str]:
    errors: list[str] = []
    backend = config.backend.lower()
    if backend not in {"facemap", "deeplabcut"}:
        errors.append("Backend must be Facemap or DeepLabCut.")
    if not Path(config.parent_model).is_file():
        errors.append("Parent model does not exist.")
    if not Path(config.training_data).exists():
        errors.append("Training data path does not exist.")
    if not Path(config.labels_or_config).is_file():
        errors.append("Labels/config file does not exist.")
    if backend == "facemap" and not Path(config.initialization_video).is_file():
        errors.append("Facemap requires an initialization video.")
    if backend == "facemap" and config.training_script and not Path(config.training_script).is_file():
        errors.append("The selected Facemap training adapter does not exist.")
    if not config.model_name.strip():
        errors.append("A new model name is required.")
    if config.epochs < 1 or config.batch_size < 1:
        errors.append("Epochs and batch size must be positive.")
    if config.learning_rate <= 0:
        errors.append("Learning rate must be positive.")
    if not re.fullmatch(r"\d{1,3}:\d{2}:\d{2}", config.walltime):
        errors.append("Walltime must use HH:MM:SS.")
    return errors


def _environment_text(backend: str) -> str:
    if backend.lower() == "facemap":
        return """name: labelforge-facemap
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - git+https://github.com/MouseLand/facemap.git
      - opencv-python-headless
"""
    return """name: labelforge-dlc
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - deeplabcut
"""


def _runner_text() -> str:
    return r'''from __future__ import annotations

import json
import os
import random
from pathlib import Path


ROOT = Path(__file__).resolve().parent
CONFIG = json.loads((ROOT / "training_manifest.json").read_text(encoding="utf-8"))


def set_seeds(seed: int) -> None:
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    try:
        import numpy as np
        np.random.seed(seed)
    except ImportError:
        pass
    try:
        import torch
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)
    except ImportError:
        pass


def run_dlc() -> None:
    import deeplabcut
    config_path = CONFIG["labels_or_config"]
    deeplabcut.train_network(
        config_path,
        shuffle=1,
        trainingsetindex=0,
        maxiters=CONFIG["epochs"],
        allow_growth=True,
    )


def run_facemap() -> None:
    # Facemap projects differ in how their CSV and image tensors are assembled.
    # The bundle deliberately validates all inputs and delegates to the versioned
    # project training script until LabelForge's common Facemap adapter is ready.
    script = ROOT / "facemap_training_adapter.py"
    if not script.exists():
        raise RuntimeError(
            "Facemap bundle is valid, but facemap_training_adapter.py is missing. "
            "Generate/copy the project adapter before submitting this run."
        )
    namespace = {"TRAINING_MANIFEST": CONFIG, "__name__": "__main__"}
    exec(compile(script.read_text(encoding="utf-8"), str(script), "exec"), namespace)


if __name__ == "__main__":
    set_seeds(int(CONFIG["random_seed"]))
    if CONFIG["backend"].lower() == "deeplabcut":
        run_dlc()
    else:
        run_facemap()
'''


def _slurm_text(config: TrainingBundleConfig) -> str:
    environment = "labelforge-facemap" if config.backend.lower() == "facemap" else "labelforge-dlc"
    account = f"#SBATCH --account={config.slurm_account}\n" if config.slurm_account else ""
    partition = f"#SBATCH --partition={config.slurm_partition}\n" if config.slurm_partition else ""
    gpu = f"#SBATCH --gres=gpu:{config.gpus}\n" if config.gpus else ""
    return f"""#!/bin/bash -l
# Generated by LabelForge. Submit with: sbatch slurm_job.sh
#SBATCH --job-name={safe_name(config.model_name)[:80]}
{account}{partition}#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={config.cpus}
{gpu}#SBATCH --mem={config.memory_gb}G
#SBATCH --time={config.walltime}
#SBATCH --output=logs/slurm-%j.out
#SBATCH --error=logs/slurm-%j.err

set -euo pipefail
mkdir -p logs
source "$HOME/.bashrc" || true
conda run -n {environment} python training_entry.py
"""


def create_bundle(config: TrainingBundleConfig) -> Path:
    errors = validate_config(config)
    if errors:
        raise ValueError("\n".join(errors))

    output_root = Path(config.output_directory).expanduser().resolve()
    bundle = output_root / f"{safe_name(config.model_name)}_training_bundle"
    if bundle.exists():
        raise FileExistsError(f"Bundle already exists: {bundle}")
    bundle.mkdir(parents=True)
    (bundle / "logs").mkdir()

    manifest = asdict(config)
    manifest["created_at"] = datetime.now().isoformat(timespec="seconds")
    manifest["bundle_format"] = 1
    manifest["source_computer"] = os.environ.get("COMPUTERNAME", "unknown")
    (bundle / "training_manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )
    (bundle / "environment.yml").write_text(
        _environment_text(config.backend), encoding="utf-8"
    )
    (bundle / "training_entry.py").write_text(_runner_text(), encoding="utf-8")
    if config.backend.lower() == "facemap" and config.training_script:
        shutil.copy2(config.training_script, bundle / "facemap_training_adapter.py")
    (bundle / "slurm_job.sh").write_text(_slurm_text(config), encoding="utf-8", newline="\n")
    env_name = "labelforge-facemap" if config.backend.lower() == "facemap" else "labelforge-dlc"
    (bundle / "run_local.bat").write_text(
        f"@echo off\r\nconda run -n {env_name} python training_entry.py\r\n",
        encoding="utf-8",
    )
    (bundle / "README.txt").write_text(
        "LabelForge training bundle\n\n"
        "1. Review training_manifest.json.\n"
        "2. Create/update the environment from environment.yml.\n"
        "3. Local: run run_local.bat.\n"
        "4. JUSUF: transfer this folder, then run sbatch slurm_job.sh.\n"
        "5. Import the completed model into LabelForge as the next version.\n",
        encoding="utf-8",
    )
    return bundle


def find_conda() -> str | None:
    candidates = [
        shutil.which("conda"),
        str(Path.home() / "miniconda3" / "Scripts" / "conda.exe"),
        r"D:\Miniconda\Scripts\conda.exe",
        r"C:\ProgramData\anaconda3\Scripts\conda.exe",
    ]
    return next((path for path in candidates if path and Path(path).is_file()), None)
